## **Importando Bíbliotecas**

In [6]:
import pandas as pd
import numpy as np
pd.set_option("display.float_format", "{:,.2f}".format)

## **Carregando Dados**

In [7]:
df = pd.read_csv('../data/TV Shows - Netflix.csv')
df

                               Titles  Year Rating  IMDB_Rating  Netflix
0                        Breaking Bad  2008    18+         9.50        1
1                     Game of Thrones  2011    18+         9.30        0
2                      Rick and Morty  2013    18+         9.20        0
3                                Dark  2017    16+         8.80        1
4                     Stranger Things  2016    16+         8.80        1
5          Avatar: The Last Airbender  2005     7+         9.20        1
6                            Sherlock  2010    16+         9.10        1
7                           Chernobyl  2019    18+         9.40        0
8                             Friends  1994    16+         8.90        0
9                          The Office  2005    16+         8.90        1
10                   Better Call Saul  2015    18+         8.70        1
11                           The Wire  2002    18+         9.30        0
12                       Supernatural  2005    16+         8.40        0
13                              Fargo  2014    18+         8.90        0
14                       Black Mirror  2011    18+         8.80        1
15                   Band of Brothers  2001    18+         9.40        0
16                    Attack on Titan  2013    16+         8.80        0
17                              House  2004    16+         8.70        0
18                        Money Heist  2017    18+         8.40        1
19                     Peaky Blinders  2013    18+         8.80        1
20                          Mr. Robot  2015    18+         8.50        0
21                            Vikings  2013    18+         8.50        0
22                       The Sopranos  1999    18+         9.20        0
23                       The Simpsons  1989     7+         8.70        0
24                    The Mandalorian  2019     7+         8.70        0
25                               Lost  2004    16+         8.30        0
26                          Westworld  2016    18+         8.70        0
27               The Umbrella Academy  2019    16+         8.00        1
28                             Narcos  2015    18+         8.80        1
29                     True Detective  2014    18+         9.00        0
30                 Marvel's Daredevil  2015    18+         8.60        1
31                 Brooklyn Nine-Nine  2013    16+         8.40        0
32                   The Walking Dead  2010    18+         8.20        1
33               Parks and Recreation  2009    16+         8.60        0
34                         Mindhunter  2017    18+         8.60        1
35                         South Park  1997    18+         8.70        0
36                              Suits  2011    16+         8.50        0
37                           Hannibal  2013    18+         8.50        1
38                             Dexter  2006    18+         8.60        0
39                          Community  2009     7+         8.50        0
40                             Fringe  2008    16+         8.40        0
41                      Modern Family  2009    16+         8.40        0
42                The Big Bang Theory  2007    16+         8.10        0
43                            Firefly  2002    16+         9.00        0
44                            Mad Men  2007    16+         8.60        0
45   Fullmetal Alchemist: Brotherhood  2009    18+         9.10        0
46                              Ozark  2017    18+         8.40        1
47                        The Witcher  2019    18+         8.20        1
48                            Lucifer  2016    16+         8.20        1
49  It's Always Sunny in Philadelphia  2005    18+         8.80        0

## **Análise Inicial**

### **Inspencionando Dados**

#### **Rotina Básica**
> Todo data scientist starta essa rotina ao pegar um novo dataset.

In [ ]:
df.shape # Retorna (linhas, colunas) do DataFrame

(50, 5)

In [ ]:
df.head(10) # Mostra as primeiras N linhas (padrão 5)

                       Titles  Year Rating  IMDB_Rating  Netflix
0                Breaking Bad  2008    18+         9.50        1
1             Game of Thrones  2011    18+         9.30        0
2              Rick and Morty  2013    18+         9.20        0
3                        Dark  2017    16+         8.80        1
4             Stranger Things  2016    16+         8.80        1
5  Avatar: The Last Airbender  2005     7+         9.20        1
6                    Sherlock  2010    16+         9.10        1
7                   Chernobyl  2019    18+         9.40        0
8                     Friends  1994    16+         8.90        0
9                  The Office  2005    16+         8.90        1

In [ ]:
df.tail(10) # Mostra as últimas N linhas (padrão 5)

                               Titles  Year Rating  IMDB_Rating  Netflix
40                             Fringe  2008    16+         8.40        0
41                      Modern Family  2009    16+         8.40        0
42                The Big Bang Theory  2007    16+         8.10        0
43                            Firefly  2002    16+         9.00        0
44                            Mad Men  2007    16+         8.60        0
45   Fullmetal Alchemist: Brotherhood  2009    18+         9.10        0
46                              Ozark  2017    18+         8.40        1
47                        The Witcher  2019    18+         8.20        1
48                            Lucifer  2016    16+         8.20        1
49  It's Always Sunny in Philadelphia  2005    18+         8.80        0

In [ ]:
df.info() # Mostra tipos, contagem de não-nulos e uso de memória

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Titles       50 non-null     str
 1   Year         50 non-null     int64
 2   Rating       50 non-null     str
 3   IMDB_Rating  50 non-null     float64
 4   Netflix      50 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 2.8 KB

In [ ]:
df.describe() # Estatísticas descritivas das colunas numéricas

          Year  IMDB_Rating  Netflix
count    50.00        50.00    50.00
mean  2,009.90         8.72     0.38
std       6.75         0.36     0.49
min   1,989.00         8.00     0.00
25%   2,005.25         8.50     0.00
50%   2,011.00         8.70     0.00
75%   2,015.00         8.90     1.00
max   2,019.00         9.50     1.00

#### **Segundo Nível**
> Aqui avançamos um pouco mais na análise inicial de um dataset, trazendo mais funções.

In [ ]:
df.dtypes # Mostra o tipo de dado de cada coluna

Titles             str
Year             int64
Rating             str
IMDB_Rating    float64
Netflix          int64
dtype: object

In [ ]:
df.columns # Lista com os nomes de todas as colunas

Index(['Titles', 'Year', 'Rating', 'IMDB_Rating', 'Netflix'], dtype='str')

In [ ]:
df.nunique() # Quantidade de valores únicos por coluna

Titles         50
Year           20
Rating          3
IMDB_Rating    16
Netflix         2
dtype: int64

In [ ]:
df.value_counts() # Frequência de cada valor em uma coluna

Titles                             Year  Rating  IMDB_Rating  Netflix
Breaking Bad                       2008  18+     9.50         1          1
Game of Thrones                    2011  18+     9.30         0          1
Rick and Morty                     2013  18+     9.20         0          1
Dark                               2017  16+     8.80         1          1
Stranger Things                    2016  16+     8.80         1          1
Avatar: The Last Airbender         2005  7+      9.20         1          1
Sherlock                           2010  16+     9.10         1          1
Chernobyl                          2019  18+     9.40         0          1
Friends                            1994  16+     8.90         0          1
The Office                         2005  16+     8.90         1          1
Better Call Saul                   2015  18+     8.70         1          1
The Wire                           2002  18+     9.30         0          1
Supernatural                       2005  16+     8.40         0          1
Fargo                              2014  18+     8.90         0          1
Black Mirror                       2011  18+     8.80         1          1
Band of Brothers                   2001  18+     9.40         0          1
Attack on Titan                    2013  16+     8.80         0          1
House                              2004  16+     8.70         0          1
Money Heist                        2017  18+     8.40         1          1
Peaky Blinders                     2013  18+     8.80         1          1
Mr. Robot                          2015  18+     8.50         0          1
Vikings                            2013  18+     8.50         0          1
The Sopranos                       1999  18+     9.20         0          1
The Simpsons                       1989  7+      8.70         0          1
The Mandalorian                    2019  7+      8.70         0          1
Lost                               2004  16+     8.30         0          1
Westworld                          2016  18+     8.70         0          1
The Umbrella Academy               2019  16+     8.00         1          1
Narcos                             2015  18+     8.80         1          1
True Detective                     2014  18+     9.00         0          1
Marvel's Daredevil                 2015  18+     8.60         1          1
Brooklyn Nine-Nine                 2013  16+     8.40         0          1
The Walking Dead                   2010  18+     8.20         1          1
Parks and Recreation               2009  16+     8.60         0          1
Mindhunter                         2017  18+     8.60         1          1
South Park                         1997  18+     8.70         0          1
Suits                              2011  16+     8.50         0          1
Hannibal                           2013  18+     8.50         1          1
Dexter                             2006  18+     8.60         0          1
Community                          2009  7+      8.50         0          1
Fringe                             2008  16+     8.40         0          1
Modern Family                      2009  16+     8.40         0          1
The Big Bang Theory                2007  16+     8.10         0          1
Firefly                            2002  16+     9.00         0          1
Mad Men                            2007  16+     8.60         0          1
Fullmetal Alchemist: Brotherhood   2009  18+     9.10         0          1
Ozark                              2017  18+     8.40         1          1
The Witcher                        2019  18+     8.20         1          1
Lucifer                            2016  16+     8.20         1          1
It's Always Sunny in Philadelphia  2005  18+     8.80         0          1
Name: count, dtype: int64

In [ ]:
df.isnull().sum() # Conta os valores nulos por coluna

Titles         0
Year           0
Rating         0
IMDB_Rating    0
Netflix        0
dtype: int64

In [ ]:
df.duplicated().sum() # Conta linhas completamente duplicadas

np.int64(0)

In [ ]:
df.sample() # Retorna N linhas aleatórias (melhor que head para datasets viciados)

                  Titles  Year Rating  IMDB_Rating  Netflix
33  Parks and Recreation  2009    16+         8.60        0

#### **Análise de uma Coluna Espacífica**
> - Aqui nós focamos em uma coluna específica para obtermos informações dela.<br>
> - As funções utilizadas aqui são melhores aplicadas para colunas que trazem valores númericos (int64 ou float64).<br>
> - Para testar, irei utilizar a coluna "IMDB_Rating".

In [26]:
df.head()

            Titles  Year Rating  IMDB_Rating  Netflix
0     Breaking Bad  2008    18+         9.50        1
1  Game of Thrones  2011    18+         9.30        0
2   Rick and Morty  2013    18+         9.20        0
3             Dark  2017    16+         8.80        1
4  Stranger Things  2016    16+         8.80        1

In [31]:
# DUAS MANEIRAS DE FAZER:

# Um por um

# imdb_rating_media = df["IMDB_Rating"].mean()
# imdb_rating_mediana = df["IMDB_Rating"].median()
# imdb_rating_desvio_padrao = df["IMDB_Rating"].std()
# imdb_rating_minimo = df["IMDB_Rating"].min()
# imdb_rating_maximo = df["IMDB_Rating"].max()
# imdb_rating_soma_total = df["IMDB_Rating"].sum()
# imdb_rating_quantidade_de_nao_nulos = df["IMDB_Rating"].count()
# imdb_rating_variancia = df["IMDB_Rating"].var()

# print(imdb_rating_media)
# print(imdb_rating_mediana)
# print(imdb_rating_desvio_padrao)
# print(imdb_rating_minimo)
# print(imdb_rating_maximo)
# print(imdb_rating_soma_total)
# print(imdb_rating_quantidade_de_nao_nulos)
# print(imdb_rating_variancia)

# Em conjunto com várias estatísticas todas de uma vez.

estatisticas_imdb = df["IMDB_Rating"].agg(["mean", "median", "std", "min", "max", "sum", "count", "var"])
estatisticas_year = df["Year"].agg(["mean", "median", "std", "min", "max", "sum", "count", "var"])

print(f'Estatísticas do IMDB:\n {estatisticas_imdb}\n')
print(f'Estatísticas do Ano de Lançamento:\n {estatisticas_year}')

# Percebe-se claramente que a segunda opção é bem melhor que a primeira dada a praticidade de formular e pedir exatamente o que se quer sem escrever demais.

Estatísticas do IMDB:
 mean       8.72
median     8.70
std        0.36
min        8.00
max        9.50
sum      436.10
count     50.00
var        0.13
Name: IMDB_Rating, dtype: float64

Estatísticas do Ano de Lançamento:
 mean       2,009.90
median     2,011.00
std            6.75
min        1,989.00
max        2,019.00
sum      100,495.00
count         50.00
var           45.52
Name: Year, dtype: float64