# **Notebook de Treino**

## **Importando Bíbliotecas**

In [2]:
import pandas as pd
import numpy as np
pd.set_option("display.float_format", "{:,.2f}".format)

## **Carregando Dados**

In [3]:
df = pd.read_csv('../data/TV Shows - Netflix.csv')
df

                               Titles  Year Rating  IMDB_Rating  Netflix
0                        Breaking Bad  2008    18+         9.50        1
1                     Game of Thrones  2011    18+         9.30        0
2                      Rick and Morty  2013    18+         9.20        0
3                                Dark  2017    16+         8.80        1
4                     Stranger Things  2016    16+         8.80        1
5          Avatar: The Last Airbender  2005     7+         9.20        1
6                            Sherlock  2010    16+         9.10        1
7                           Chernobyl  2019    18+         9.40        0
8                             Friends  1994    16+         8.90        0
9                          The Office  2005    16+         8.90        1
10                   Better Call Saul  2015    18+         8.70        1
11                           The Wire  2002    18+         9.30        0
12                       Supernatural  2005    16+         8.40        0
13                              Fargo  2014    18+         8.90        0
14                       Black Mirror  2011    18+         8.80        1
15                   Band of Brothers  2001    18+         9.40        0
16                    Attack on Titan  2013    16+         8.80        0
17                              House  2004    16+         8.70        0
18                        Money Heist  2017    18+         8.40        1
19                     Peaky Blinders  2013    18+         8.80        1
20                          Mr. Robot  2015    18+         8.50        0
21                            Vikings  2013    18+         8.50        0
22                       The Sopranos  1999    18+         9.20        0
23                       The Simpsons  1989     7+         8.70        0
24                    The Mandalorian  2019     7+         8.70        0
25                               Lost  2004    16+         8.30        0
26                          Westworld  2016    18+         8.70        0
27               The Umbrella Academy  2019    16+         8.00        1
28                             Narcos  2015    18+         8.80        1
29                     True Detective  2014    18+         9.00        0
30                 Marvel's Daredevil  2015    18+         8.60        1
31                 Brooklyn Nine-Nine  2013    16+         8.40        0
32                   The Walking Dead  2010    18+         8.20        1
33               Parks and Recreation  2009    16+         8.60        0
34                         Mindhunter  2017    18+         8.60        1
35                         South Park  1997    18+         8.70        0
36                              Suits  2011    16+         8.50        0
37                           Hannibal  2013    18+         8.50        1
38                             Dexter  2006    18+         8.60        0
39                          Community  2009     7+         8.50        0
40                             Fringe  2008    16+         8.40        0
41                      Modern Family  2009    16+         8.40        0
42                The Big Bang Theory  2007    16+         8.10        0
43                            Firefly  2002    16+         9.00        0
44                            Mad Men  2007    16+         8.60        0
45   Fullmetal Alchemist: Brotherhood  2009    18+         9.10        0
46                              Ozark  2017    18+         8.40        1
47                        The Witcher  2019    18+         8.20        1
48                            Lucifer  2016    16+         8.20        1
49  It's Always Sunny in Philadelphia  2005    18+         8.80        0

## **Análise Inicial**

### **Inspencionando Dados**

#### **Primeiro Nível (Rotina Básica)**
> Todo data scientist starta essa rotina ao pegar um novo dataset.

In [4]:
df.shape # Retorna (linhas, colunas) do DataFrame

(50, 5)

In [5]:
df.head(10) # Mostra as primeiras N linhas (padrão 5)

                       Titles  Year Rating  IMDB_Rating  Netflix
0                Breaking Bad  2008    18+         9.50        1
1             Game of Thrones  2011    18+         9.30        0
2              Rick and Morty  2013    18+         9.20        0
3                        Dark  2017    16+         8.80        1
4             Stranger Things  2016    16+         8.80        1
5  Avatar: The Last Airbender  2005     7+         9.20        1
6                    Sherlock  2010    16+         9.10        1
7                   Chernobyl  2019    18+         9.40        0
8                     Friends  1994    16+         8.90        0
9                  The Office  2005    16+         8.90        1

In [6]:
df.tail(10) # Mostra as últimas N linhas (padrão 5)

                               Titles  Year Rating  IMDB_Rating  Netflix
40                             Fringe  2008    16+         8.40        0
41                      Modern Family  2009    16+         8.40        0
42                The Big Bang Theory  2007    16+         8.10        0
43                            Firefly  2002    16+         9.00        0
44                            Mad Men  2007    16+         8.60        0
45   Fullmetal Alchemist: Brotherhood  2009    18+         9.10        0
46                              Ozark  2017    18+         8.40        1
47                        The Witcher  2019    18+         8.20        1
48                            Lucifer  2016    16+         8.20        1
49  It's Always Sunny in Philadelphia  2005    18+         8.80        0

In [7]:
df.info() # Mostra tipos, contagem de não-nulos e uso de memória

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Titles       50 non-null     str
 1   Year         50 non-null     int64
 2   Rating       50 non-null     str
 3   IMDB_Rating  50 non-null     float64
 4   Netflix      50 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 2.8 KB

In [8]:
df.describe() # Estatísticas descritivas das colunas numéricas

          Year  IMDB_Rating  Netflix
count    50.00        50.00    50.00
mean  2,009.90         8.72     0.38
std       6.75         0.36     0.49
min   1,989.00         8.00     0.00
25%   2,005.25         8.50     0.00
50%   2,011.00         8.70     0.00
75%   2,015.00         8.90     1.00
max   2,019.00         9.50     1.00

In [9]:
df.describe(include="all") # A diferença desse .describe() é o parâmetro include="all", esse parâmetro traz todas as informações, enquanto o anterior traz apenas as informações numéricas. Consequentemente ele traz muitos dados como NaN (nulos), porém não são nulos de verdade.

              Titles     Year Rating  IMDB_Rating  Netflix
count             50    50.00     50        50.00    50.00
unique            50      NaN      3          NaN      NaN
top     Breaking Bad      NaN    18+          NaN      NaN
freq               1      NaN     27          NaN      NaN
mean             NaN 2,009.90    NaN         8.72     0.38
std              NaN     6.75    NaN         0.36     0.49
min              NaN 1,989.00    NaN         8.00     0.00
25%              NaN 2,005.25    NaN         8.50     0.00
50%              NaN 2,011.00    NaN         8.70     0.00
75%              NaN 2,015.00    NaN         8.90     1.00
max              NaN 2,019.00    NaN         9.50     1.00

In [10]:
df.describe(include="object") # Com esse describ, deferente do "all", conseguimos trazer apenas as que são colunas com textos.

/tmp/ipykernel_1801/2597218053.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object") # Com esse describ, deferente do "all", conseguimos trazer apenas as que são colunas com textos.

              Titles Rating
count             50     50
unique            50      3
top     Breaking Bad    18+
freq               1     27

In [11]:
df.describe(percentiles=[.01, .1, .25, .5, .75, .9, .95, .99]) # Com esse describe, coneguimos modificar os percentis. O padrão é apenas 25%, 50% e 75%. Com esse colocamos mais percentis.

# Isso é útil para detectar outliers extremos. O percentil 99 te diz onde estão os 1% maiores valores — muito usado em análise de fraude, por exemplo.

          Year  IMDB_Rating  Netflix
count    50.00        50.00    50.00
mean  2,009.90         8.72     0.38
std       6.75         0.36     0.49
min   1,989.00         8.00     0.00
1%    1,991.45         8.05     0.00
10%   2,001.90         8.29     0.00
25%   2,005.25         8.50     0.00
50%   2,011.00         8.70     0.00
75%   2,015.00         8.90     1.00
90%   2,017.00         9.21     1.00
95%   2,019.00         9.36     1.00
99%   2,019.00         9.45     1.00
max   2,019.00         9.50     1.00

#### **Segundo Nível**
> Aqui avançamos um pouco mais na análise inicial de um dataset, trazendo mais funções.

In [12]:
df.dtypes # Mostra o tipo de dado de cada coluna

Titles             str
Year             int64
Rating             str
IMDB_Rating    float64
Netflix          int64
dtype: object

In [13]:
df.columns # Lista com os nomes de todas as colunas

Index(['Titles', 'Year', 'Rating', 'IMDB_Rating', 'Netflix'], dtype='str')

In [14]:
df.nunique() # Quantidade de valores únicos por coluna

Titles         50
Year           20
Rating          3
IMDB_Rating    16
Netflix         2
dtype: int64

In [15]:
df.value_counts() # Frequência de cada valor em uma coluna

Titles                             Year  Rating  IMDB_Rating  Netflix
Breaking Bad                       2008  18+     9.50         1          1
Game of Thrones                    2011  18+     9.30         0          1
Rick and Morty                     2013  18+     9.20         0          1
Dark                               2017  16+     8.80         1          1
Stranger Things                    2016  16+     8.80         1          1
Avatar: The Last Airbender         2005  7+      9.20         1          1
Sherlock                           2010  16+     9.10         1          1
Chernobyl                          2019  18+     9.40         0          1
Friends                            1994  16+     8.90         0          1
The Office                         2005  16+     8.90         1          1
Better Call Saul                   2015  18+     8.70         1          1
The Wire                           2002  18+     9.30         0          1
Supernatural                       2005  16+     8.40         0          1
Fargo                              2014  18+     8.90         0          1
Black Mirror                       2011  18+     8.80         1          1
Band of Brothers                   2001  18+     9.40         0          1
Attack on Titan                    2013  16+     8.80         0          1
House                              2004  16+     8.70         0          1
Money Heist                        2017  18+     8.40         1          1
Peaky Blinders                     2013  18+     8.80         1          1
Mr. Robot                          2015  18+     8.50         0          1
Vikings                            2013  18+     8.50         0          1
The Sopranos                       1999  18+     9.20         0          1
The Simpsons                       1989  7+      8.70         0          1
The Mandalorian                    2019  7+      8.70         0          1
Lost                               2004  16+     8.30         0          1
Westworld                          2016  18+     8.70         0          1
The Umbrella Academy               2019  16+     8.00         1          1
Narcos                             2015  18+     8.80         1          1
True Detective                     2014  18+     9.00         0          1
Marvel's Daredevil                 2015  18+     8.60         1          1
Brooklyn Nine-Nine                 2013  16+     8.40         0          1
The Walking Dead                   2010  18+     8.20         1          1
Parks and Recreation               2009  16+     8.60         0          1
Mindhunter                         2017  18+     8.60         1          1
South Park                         1997  18+     8.70         0          1
Suits                              2011  16+     8.50         0          1
Hannibal                           2013  18+     8.50         1          1
Dexter                             2006  18+     8.60         0          1
Community                          2009  7+      8.50         0          1
Fringe                             2008  16+     8.40         0          1
Modern Family                      2009  16+     8.40         0          1
The Big Bang Theory                2007  16+     8.10         0          1
Firefly                            2002  16+     9.00         0          1
Mad Men                            2007  16+     8.60         0          1
Fullmetal Alchemist: Brotherhood   2009  18+     9.10         0          1
Ozark                              2017  18+     8.40         1          1
The Witcher                        2019  18+     8.20         1          1
Lucifer                            2016  16+     8.20         1          1
It's Always Sunny in Philadelphia  2005  18+     8.80         0          1
Name: count, dtype: int64

In [16]:
df.isnull().sum() # Conta os valores nulos por coluna

Titles         0
Year           0
Rating         0
IMDB_Rating    0
Netflix        0
dtype: int64

In [17]:
df.duplicated().sum() # Conta linhas completamente duplicadas

np.int64(0)

In [18]:
df.sample() # Retorna N linhas aleatórias (melhor que head para datasets viciados)

     Titles  Year Rating  IMDB_Rating  Netflix
6  Sherlock  2010    16+         9.10        1

#### **Análise de uma Coluna Específica**
> - Aqui nós focamos em uma coluna específica para obtermos informações dela.<br>
> - As funções utilizadas aqui são melhores aplicadas para colunas que trazem valores númericos (int64 ou float64).<br>
> - Para testar, irei utilizar a coluna "IMDB_Rating".

In [19]:
df.head()

            Titles  Year Rating  IMDB_Rating  Netflix
0     Breaking Bad  2008    18+         9.50        1
1  Game of Thrones  2011    18+         9.30        0
2   Rick and Morty  2013    18+         9.20        0
3             Dark  2017    16+         8.80        1
4  Stranger Things  2016    16+         8.80        1

In [20]:
# DUAS MANEIRAS DE FAZER:

# Um por um

# imdb_rating_media = df["IMDB_Rating"].mean()
# imdb_rating_mediana = df["IMDB_Rating"].median()
# imdb_rating_desvio_padrao = df["IMDB_Rating"].std()
# imdb_rating_minimo = df["IMDB_Rating"].min()
# imdb_rating_maximo = df["IMDB_Rating"].max()
# imdb_rating_soma_total = df["IMDB_Rating"].sum()
# imdb_rating_quantidade_de_nao_nulos = df["IMDB_Rating"].count()
# imdb_rating_variancia = df["IMDB_Rating"].var()

# print(imdb_rating_media)
# print(imdb_rating_mediana)
# print(imdb_rating_desvio_padrao)
# print(imdb_rating_minimo)
# print(imdb_rating_maximo)
# print(imdb_rating_soma_total)
# print(imdb_rating_quantidade_de_nao_nulos)
# print(imdb_rating_variancia)

# Em conjunto com várias estatísticas todas de uma vez.

estatisticas_imdb = df["IMDB_Rating"].agg(["mean", "median", "std", "min", "max", "sum", "count", "var"])
estatisticas_year = df["Year"].agg(["mean", "median", "std", "min", "max", "sum", "count", "var"])

print(f'Estatísticas do IMDB:\n {estatisticas_imdb}\n')
print(f'Estatísticas do Ano de Lançamento:\n {estatisticas_year}')

# Percebe-se claramente que a segunda opção é bem melhor que a primeira dada a praticidade de formular e pedir exatamente o que se quer sem escrever demais.

Estatísticas do IMDB:
 mean       8.72
median     8.70
std        0.36
min        8.00
max        9.50
sum      436.10
count     50.00
var        0.13
Name: IMDB_Rating, dtype: float64

Estatísticas do Ano de Lançamento:
 mean       2,009.90
median     2,011.00
std            6.75
min        1,989.00
max        2,019.00
sum      100,495.00
count         50.00
var           45.52
Name: Year, dtype: float64

In [21]:
df['Titles']

0                          Breaking Bad
1                       Game of Thrones
2                        Rick and Morty
3                                  Dark
4                       Stranger Things
5            Avatar: The Last Airbender
6                              Sherlock
7                             Chernobyl
8                               Friends
9                            The Office
10                     Better Call Saul
11                             The Wire
12                         Supernatural
13                                Fargo
14                         Black Mirror
15                     Band of Brothers
16                      Attack on Titan
17                                House
18                          Money Heist
19                       Peaky Blinders
20                            Mr. Robot
21                              Vikings
22                         The Sopranos
23                         The Simpsons
24                      The Mandalorian
25                                 Lost
26                            Westworld
27                 The Umbrella Academy
28                               Narcos
29                       True Detective
30                   Marvel's Daredevil
31                   Brooklyn Nine-Nine
32                     The Walking Dead
33                 Parks and Recreation
34                           Mindhunter
35                           South Park
36                                Suits
37                             Hannibal
38                               Dexter
39                            Community
40                               Fringe
41                        Modern Family
42                  The Big Bang Theory
43                              Firefly
44                              Mad Men
45     Fullmetal Alchemist: Brotherhood
46                                Ozark
47                          The Witcher
48                              Lucifer
49    It's Always Sunny in Philadelphia
Name: Titles, dtype: str

In [23]:
df[['Titles', 'IMDB_Rating']]

                               Titles  IMDB_Rating
0                        Breaking Bad         9.50
1                     Game of Thrones         9.30
2                      Rick and Morty         9.20
3                                Dark         8.80
4                     Stranger Things         8.80
5          Avatar: The Last Airbender         9.20
6                            Sherlock         9.10
7                           Chernobyl         9.40
8                             Friends         8.90
9                          The Office         8.90
10                   Better Call Saul         8.70
11                           The Wire         9.30
12                       Supernatural         8.40
13                              Fargo         8.90
14                       Black Mirror         8.80
15                   Band of Brothers         9.40
16                    Attack on Titan         8.80
17                              House         8.70
18                        Money Heist         8.40
19                     Peaky Blinders         8.80
20                          Mr. Robot         8.50
21                            Vikings         8.50
22                       The Sopranos         9.20
23                       The Simpsons         8.70
24                    The Mandalorian         8.70
25                               Lost         8.30
26                          Westworld         8.70
27               The Umbrella Academy         8.00
28                             Narcos         8.80
29                     True Detective         9.00
30                 Marvel's Daredevil         8.60
31                 Brooklyn Nine-Nine         8.40
32                   The Walking Dead         8.20
33               Parks and Recreation         8.60
34                         Mindhunter         8.60
35                         South Park         8.70
36                              Suits         8.50
37                           Hannibal         8.50
38                             Dexter         8.60
39                          Community         8.50
40                             Fringe         8.40
41                      Modern Family         8.40
42                The Big Bang Theory         8.10
43                            Firefly         9.00
44                            Mad Men         8.60
45   Fullmetal Alchemist: Brotherhood         9.10
46                              Ozark         8.40
47                        The Witcher         8.20
48                            Lucifer         8.20
49  It's Always Sunny in Philadelphia         8.80

In [26]:
# Series — uma dimensão
df["IMDB_Rating"]

# DataFrame — duas dimensões
df[["IMDB_Rating"]]

    IMDB_Rating
0          9.50
1          9.30
2          9.20
3          8.80
4          8.80
5          9.20
6          9.10
7          9.40
8          8.90
9          8.90
10         8.70
11         9.30
12         8.40
13         8.90
14         8.80
15         9.40
16         8.80
17         8.70
18         8.40
19         8.80
20         8.50
21         8.50
22         9.20
23         8.70
24         8.70
25         8.30
26         8.70
27         8.00
28         8.80
29         9.00
30         8.60
31         8.40
32         8.20
33         8.60
34         8.60
35         8.70
36         8.50
37         8.50
38         8.60
39         8.50
40         8.40
41         8.40
42         8.10
43         9.00
44         8.60
45         9.10
46         8.40
47         8.20
48         8.20
49         8.80

In [27]:
# Só colunas numéricas
df.select_dtypes(include="number")

    Year  IMDB_Rating  Netflix
0   2008         9.50        1
1   2011         9.30        0
2   2013         9.20        0
3   2017         8.80        1
4   2016         8.80        1
5   2005         9.20        1
6   2010         9.10        1
7   2019         9.40        0
8   1994         8.90        0
9   2005         8.90        1
10  2015         8.70        1
11  2002         9.30        0
12  2005         8.40        0
13  2014         8.90        0
14  2011         8.80        1
15  2001         9.40        0
16  2013         8.80        0
17  2004         8.70        0
18  2017         8.40        1
19  2013         8.80        1
20  2015         8.50        0
21  2013         8.50        0
22  1999         9.20        0
23  1989         8.70        0
24  2019         8.70        0
25  2004         8.30        0
26  2016         8.70        0
27  2019         8.00        1
28  2015         8.80        1
29  2014         9.00        0
30  2015         8.60        1
31  2013         8.40        0
32  2010         8.20        1
33  2009         8.60        0
34  2017         8.60        1
35  1997         8.70        0
36  2011         8.50        0
37  2013         8.50        1
38  2006         8.60        0
39  2009         8.50        0
40  2008         8.40        0
41  2009         8.40        0
42  2007         8.10        0
43  2002         9.00        0
44  2007         8.60        0
45  2009         9.10        0
46  2017         8.40        1
47  2019         8.20        1
48  2016         8.20        1
49  2005         8.80        0

In [28]:
# Só colunas de texto
df.select_dtypes(include="object")

/tmp/ipykernel_1801/2490026179.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object")

                               Titles Rating
0                        Breaking Bad    18+
1                     Game of Thrones    18+
2                      Rick and Morty    18+
3                                Dark    16+
4                     Stranger Things    16+
5          Avatar: The Last Airbender     7+
6                            Sherlock    16+
7                           Chernobyl    18+
8                             Friends    16+
9                          The Office    16+
10                   Better Call Saul    18+
11                           The Wire    18+
12                       Supernatural    16+
13                              Fargo    18+
14                       Black Mirror    18+
15                   Band of Brothers    18+
16                    Attack on Titan    16+
17                              House    16+
18                        Money Heist    18+
19                     Peaky Blinders    18+
20                          Mr. Robot    18+
21                            Vikings    18+
22                       The Sopranos    18+
23                       The Simpsons     7+
24                    The Mandalorian     7+
25                               Lost    16+
26                          Westworld    18+
27               The Umbrella Academy    16+
28                             Narcos    18+
29                     True Detective    18+
30                 Marvel's Daredevil    18+
31                 Brooklyn Nine-Nine    16+
32                   The Walking Dead    18+
33               Parks and Recreation    16+
34                         Mindhunter    18+
35                         South Park    18+
36                              Suits    16+
37                           Hannibal    18+
38                             Dexter    18+
39                          Community     7+
40                             Fringe    16+
41                      Modern Family    16+
42                The Big Bang Theory    16+
43                            Firefly    16+
44                            Mad Men    16+
45   Fullmetal Alchemist: Brotherhood    18+
46                              Ozark    18+
47                        The Witcher    18+
48                            Lucifer    16+
49  It's Always Sunny in Philadelphia    18+

In [31]:
# Excluindo um tipo
df.select_dtypes(exclude="number")

                               Titles Rating
0                        Breaking Bad    18+
1                     Game of Thrones    18+
2                      Rick and Morty    18+
3                                Dark    16+
4                     Stranger Things    16+
5          Avatar: The Last Airbender     7+
6                            Sherlock    16+
7                           Chernobyl    18+
8                             Friends    16+
9                          The Office    16+
10                   Better Call Saul    18+
11                           The Wire    18+
12                       Supernatural    16+
13                              Fargo    18+
14                       Black Mirror    18+
15                   Band of Brothers    18+
16                    Attack on Titan    16+
17                              House    16+
18                        Money Heist    18+
19                     Peaky Blinders    18+
20                          Mr. Robot    18+
21                            Vikings    18+
22                       The Sopranos    18+
23                       The Simpsons     7+
24                    The Mandalorian     7+
25                               Lost    16+
26                          Westworld    18+
27               The Umbrella Academy    16+
28                             Narcos    18+
29                     True Detective    18+
30                 Marvel's Daredevil    18+
31                 Brooklyn Nine-Nine    16+
32                   The Walking Dead    18+
33               Parks and Recreation    16+
34                         Mindhunter    18+
35                         South Park    18+
36                              Suits    16+
37                           Hannibal    18+
38                             Dexter    18+
39                          Community     7+
40                             Fringe    16+
41                      Modern Family    16+
42                The Big Bang Theory    16+
43                            Firefly    16+
44                            Mad Men    16+
45   Fullmetal Alchemist: Brotherhood    18+
46                              Ozark    18+
47                        The Witcher    18+
48                            Lucifer    16+
49  It's Always Sunny in Philadelphia    18+